options_resolver_examples:
    resource: "@OptionsResolverExamplesBundle/Resources/config/routing.yml"
    prefix:   /optionsresolver

config_examples:
    resource: "@ConfigExamplesBundle/Resources/config/routing.yml"
    prefix:   /config

app:
    resource: @AppBundle/Controller/
    type:     annotation
