#    config_examples.example:
#        class: ConfigExamplesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    config_path: "%kernel.root_dir%/config/config"
    abtests_path: "%kernel.root_dir%/config/abtests"
    attests_cache_path: "%kernel.cache_dir%/abtests"
services:
    config_examples.config_controller:
        class: ConfigExamplesBundle\Controller\ConfigController
        arguments:
            - @config_examples.config_service
    config_examples.config_service:
        class: ConfigExamplesBundle\Services\ConfigService
        arguments: [@config_examples.config_delegating_loader]
#delegating loader    
    config_examples.config_delegating_loader:
        class: Symfony\Component\Config\Loader\DelegatingLoader
        arguments: [@config_examples.config_resolver]
    #chain of responsability
    config_examples.config_resolver:
        class: Symfony\Component\Config\Loader\LoaderResolver
        arguments: 
            - [@config_examples.yaml_loader, @config_examples.abtest_loader]
#loaders
    config_examples.yaml_loader:
        class: ConfigExamplesBundle\Loader\YamlFileLoader
        arguments: [@config_examples.yaml_locator]
    config_examples.abtest_loader:
        class: ConfigExamplesBundle\Loader\AbtestFileLoader
        arguments: [@config_examples.abtest_locator]
    
#locators
    config_examples.yaml_locator:
        class: ConfigExamplesBundle\Locator\YamlLocator
        arguments: [%config_path%, @config_examples.file_locator]
    config_examples.abtest_locator:
        class: ConfigExamplesBundle\Locator\AbtestLocator
        arguments: [%abtests_path%, @config_examples.file_locator]
#the default locator
    config_examples.file_locator:
        class: Symfony\Component\Config\FileLocator
#        arguments: [%config_path%]
#cache warmer
    config_examples.abtest_cache_warmer:
        class: ConfigExamplesBundle\CacheWarmer\AbtestCacheWarmer
        arguments: [@config_examples.abtest_loader, %attests_cache_path%]
        tags:
            - {kernel.cache_warmer}